name: Build WhirlyOS ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y live-build debootstrap xorriso squashfs-tools

    - name: Build ISO
      run: |
        sudo lb clean
        sudo lb config --distribution bookworm \
                       --archive-areas "main contrib non-free" \
                       --mirror-bootstrap http://deb.debian.org/debian \
                       --mirror-chroot http://deb.debian.org/debian \
                       --mirror-binary http://deb.debian.org/debian
        sudo lb build

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: whirlyos-iso
        path: ./live-image-amd64.hybrid.iso
